# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'categorizador_covid_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatogorizadorCovidDialogBase(object):
    def setupUi(self, CatogorizadorCovidDialogBase):
        CatogorizadorCovidDialogBase.setObjectName("CatogorizadorCovidDialogBase")
        CatogorizadorCovidDialogBase.resize(397, 484)
        CatogorizadorCovidDialogBase.setMinimumSize(QtCore.QSize(397, 484))
        CatogorizadorCovidDialogBase.setMaximumSize(QtCore.QSize(397, 484))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/categorizador_covid/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CatogorizadorCovidDialogBase.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(CatogorizadorCovidDialogBase)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 16))
        self.label.setObjectName("label")
        self.combobox_shapes = QtWidgets.QComboBox(CatogorizadorCovidDialogBase)
        self.combobox_shapes.setGeometry(QtCore.QRect(10, 40, 351, 26))
        self.combobox_shapes.setObjectName("combobox_shapes")
        self.btn_shapes = QtWidgets.QPushButton(CatogorizadorCovidDialogBase)
        self.btn_shapes.setGeometry(QtCore.QRect(365, 40, 31, 27))
        self.btn_shapes.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/categorizador_covid/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_shapes.setIcon(icon1)
        self.btn_shapes.setObjectName("btn_shapes")
        self.groupBox = QtWidgets.QGroupBox(CatogorizadorCovidDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(20, 80, 331, 131))
        self.groupBox.setObjectName("groupBox")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(5, 31, 331, 111))
        self.listWidget.setObjectName("listWidget")
        self.btn_borrar = QtWidgets.QPushButton(CatogorizadorCovidDialogBase)
        self.btn_borrar.setGeometry(QtCore.QRect(370, 160, 16, 27))
        self.btn_borrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/categorizador_covid/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_borrar.setIcon(icon2)
        self.btn_borrar.setObjectName("btn_borrar")
        self.label_2 = QtWidgets.QLabel(CatogorizadorCovidDialogBase)
        self.label_2.setGeometry(QtCore.QRect(20, 240, 371, 16))
        self.label_2.setObjectName("label_2")
        self.combobox_campo = QtWidgets.QComboBox(CatogorizadorCovidDialogBase)
        self.combobox_campo.setGeometry(QtCore.QRect(20, 270, 331, 26))
        self.combobox_campo.setObjectName("combobox_campo")
        self.label_3 = QtWidgets.QLabel(CatogorizadorCovidDialogBase)
        self.label_3.setGeometry(QtCore.QRect(20, 310, 341, 16))
        self.label_3.setObjectName("label_3")
        self.path_salida = QtWidgets.QLineEdit(CatogorizadorCovidDialogBase)
        self.path_salida.setGeometry(QtCore.QRect(20, 340, 331, 28))
        self.path_salida.setReadOnly(True)
        self.path_salida.setObjectName("path_salida")
        self.btn_salida = QtWidgets.QPushButton(CatogorizadorCovidDialogBase)
        self.btn_salida.setGeometry(QtCore.QRect(370, 340, 16, 27))
        self.btn_salida.setText("")
        self.btn_salida.setIcon(icon1)
        self.btn_salida.setObjectName("btn_salida")
        self.horizontalLayoutWidget = QtWidgets.QWidget(CatogorizadorCovidDialogBase)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 380, 371, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_aceptar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.horizontalLayout.addWidget(self.btn_aceptar)
        self.btn_cancelar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)

        self.retranslateUi(CatogorizadorCovidDialogBase)
        QtCore.QMetaObject.connectSlotsByName(CatogorizadorCovidDialogBase)

    def retranslateUi(self, CatogorizadorCovidDialogBase):
        _translate = QtCore.QCoreApplication.translate
        CatogorizadorCovidDialogBase.setWindowTitle(_translate("CatogorizadorCovidDialogBase", "Categorizador Covid"))
        self.label.setText(_translate("CatogorizadorCovidDialogBase", "Selecciona los shapes a utilizar:"))
        self.groupBox.setTitle(_translate("CatogorizadorCovidDialogBase", "Shapes Seleccionados"))
        self.label_2.setText(_translate("CatogorizadorCovidDialogBase", "Selecciona el campo en comun"))
        self.label_3.setText(_translate("CatogorizadorCovidDialogBase", "Selecciona la ruta de almacenamiento"))
        self.btn_aceptar.setText(_translate("CatogorizadorCovidDialogBase", "Aceptar"))
        self.btn_cancelar.setText(_translate("CatogorizadorCovidDialogBase", "Cancelar"))
        
#PyQT5
from .resources import *

